# Generated by Django 5.2.10 on 2026-01-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='species_images/')),
                ('description', models.CharField(max_length=120)),
                ('cash_value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
